## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

In [2]:
import os
import numpy as np
import pandas as pd

In [3]:
# 設定 data_path
dir_data = './data/'

In [4]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [16]:
t = app_train.shape
t

(307511, 122)

#### 列出所有欄位

In [28]:
for column in app_train:
    print(app_train[column])

0         100002
1         100003
2         100004
3         100006
4         100007
5         100008
6         100009
7         100010
8         100011
9         100012
10        100014
11        100015
12        100016
13        100017
14        100018
15        100019
16        100020
17        100021
18        100022
19        100023
20        100024
21        100025
22        100026
23        100027
24        100029
25        100030
26        100031
27        100032
28        100033
29        100034
30        100035
31        100036
32        100037
33        100039
34        100040
35        100041
36        100043
37        100044
38        100045
39        100046
40        100047
41        100048
42        100049
43        100050
44        100051
45        100052
46        100053
47        100054
48        100055
49        100056
           ...
307461    456200
307462    456201
307463    456203
307464    456204
307465    456205
307466    456206
307467    456207
307468    456208
307469    456209
307470    456210
307471    456211
307472    456212
307473    456213
307474    456214
307475    456215
307476    456216
307477    456217
307478    456218
307479    456219
307480    456220
307481    456225
307482    456226
307483    456227
307484    456228
307485    456229
307486    456230
307487    456231
307488    456232
307489    456233
307490    456234
307491    456235
307492    456236
307493    456237
307494    456238
307495    456239
307496    456240
307497    456241
307498    456242
307499    456243
307500    456244
307501    456245
307502    456246
307503    456247
307504    456248
307505    456249
307506    456251
307507    456252
307508    456253
307509    456254
307510    456255
Name: SK_ID_CURR, Length: 307511, dtype: int64
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        1
27        0
28        0
29        0
30        0
31        0
32        0
33        0
34        0
35        0
36        0
37        0
38        0
39        0
40        1
41        0
42        1
43        0
44        0
45        0
46        0
47        0
48        0
49        0
         ..
307461    0
307462    0
307463    0
307464    0
307465    0
307466    0
307467    0
307468    0
307469    0
307470    0
307471    0
307472    0
307473    0
307474    0
307475    1
307476    0
307477    0
307478    0
307479    0
307480    0
307481    1
307482    0
307483    0
307484    0
307485    0
307486    0
307487    0
307488    0
307489    1
307490    0
307491    0
307492    0
307493    0
307494    0
307495    0
307496    0
307497    0
307498    0
307499    0
307500    0
307501    0
307502    0
307503    0
307504    0
307505    0
307506    0
307507    0
307508    0
307509    1
307510    0
Name: TARGET, Length: 307511, dtype: int64
0              Cash loans
1              Cash loans
2         Revolving loans
3              Cash loans
4              Cash loans
5              Cash loans
6              Cash loans
7              Cash loans
8              Cash loans
9         Revolving loans
10             Cash loans
11             Cash loans
12             Cash loans
13             Cash loans
14             Cash loans
15             Cash loans
16             Cash loans
17        Revolving loans
18        Revolving loans
19             Cash loans
20        Revolving loans
21             Cash loans
22             Cash loans
23             Cash loans
24             Cash loans
25             Cash loans
26             Cash loans
27             Cash loans
28             Cash loans
29        Revolving loans
30             Cash loans
31             Cash loans
32             Cash loans
33             Cash loans
34             Cash loans
35             Cash loans
36             Cash loans
37             Cash loans
38             Cash loans
39        Revolving loans
40             Cash loans
41             Cash loans
42             Cash loans
43             Cash loans
44             Cash loans
45        Revolving loans
46             Cash loans
47             Cash loans
48             Cash loans
49             Cash loans
               ...
307461         Cash loans
307462         Cash loans
307463         Cash loans
307464         Cash loans
307465         Cash loans
307466         Cash loans
307467    Revolving loans
307468         Cash loans
307469         Cash loans
307470         Cash loans
307471         Cash loans
307472         Cash loans
307473         Cash loans
307474         Cash loans
307475         Cash loans
307476         Cash loans
307477         Cash loans
307478         Cash loans
307479         Cash loans
307480         Cash loans
307481         Cash loans
307482         Cash loans
307483         Cash loans
307484         Cash loans
307485    Revolving loans
307486         Cash loans
307487         Cash loans
307488         Cash loans
307489         Cash loans
307490         Cash loans
307491         Cash loans
307492         Cash loans
307493         Cash loans
307494         Cash loans
307495         Cash loans
307496    Revolving loans
307497         Cash loans
307498         Cash loans
307499         Cash loans
307500         Cash loans
307501         Cash loans
307502         Cash loans
307503         Cash loans
307504         Cash loans
307505         Cash loans
307506         Cash loans
307507         Cash loans
307508         Cash loans
307509         Cash loans
307510         Cash loans
Name: NAME_CONTRACT_TYPE, Length: 307511, dtype: object
0         M
1         F
2         M
3         F
4         M
5         M
6         F
7         M
8         F
9         M
10        F
11        F
12        F
13        M
14        F
15        M
16        M
17        F
18        F
19        F
20        M
21        F
22        F
23        F
24        M
25        F
26        F
27        M
28        M
29        M
30        F
31        F
32        F
33        M
34        F
35        F
36        F
37        M
38        F
39        M
40        M
41        F
42        F
43        F
44        M
45        F
46        F
47        F
48        F
49        M
         ..
307461    F
307462    F
307463    F
307464    F
307465    F
307466    F
307467    F
307468    F
307469    F
307470    F
307471    F
307472    F
307473    F
307474    M
307475    F
307476    F
307477    F
307478    F
307479    F
307480    F
307481    M
307482    F
307483    F
307484    F
307485    F
307486    F
307487    M
307488    F
307489    F
307490    M
307491    M
307492    M
307493    F
307494    M
307495    M
307496    F
307497    F
307498    M
307499    F
307500    F
307501    F
307502    F
307503    F
307504    F
307505    F
307506    M
307507    F
307508    F
307509    F
307510    F
Name: CODE_GENDER, Length: 307511, dtype: object
0         N
1         N
2         Y
3         N
4         N
5         N
6         Y
7         Y
8         N
9         N
10        N
11        N
12        N
13        Y
14        N
15        Y
16        N
17        N
18        N
19        N
20        Y
21        Y
22        N
23        N
24        Y
25        N
26        N
27        N
28        Y
29        N
30        N
31        N
32        N
33        Y
34        N
35        N
36        N
37        N
38        N
39        Y
40        N
41        N
42        N
43        N
44        N
45        N
46        N
47        N
48        N
49        Y
         ..
307461    N
307462    Y
307463    N
307464    N
307465    N
307466    N
307467    N
307468    N
307469    N
307470    N
307471    N
307472    N
307473    Y
307474    Y
307475    N
307476    N
307477    N
307478    N
307479    N
307480    N
307481    N
307482    Y
307483    N
307484    Y
307485    N
307486    Y
307487    N
307488    N
307489    N
307490    N
307491    Y
307492    Y
307493    N
307494    Y
307495    Y
307496    N
307497    Y
307498    Y
307499    N
307500    N
307501    N
307502    N
307503    N
307504    N
307505    N
307506    N
307507    N
307508    N
307509    N
307510    N
Name: FLAG_OWN_CAR, Length: 307511, dtype: object
0         Y
1         N
2         Y
3         Y
4         Y
5         Y
6         Y
7         Y
8         Y
9         Y
10        Y
11        Y
12        Y
13        N
14        Y
15        Y
16        N
17        Y
18        Y
19        Y
20        Y
21        Y
22        N
23        Y
24        N
25        Y
26        Y
27        Y
28        Y
29        Y
30        Y
31        Y
32        N
33        N
34        Y
35        N
36        Y
37        Y
38        Y
39        Y
40        Y
41        Y
42        N
43        Y
44        Y
45        Y
46        Y
47        Y
48        N
49        Y
         ..
307461    N
307462    Y
307463    Y
307464    Y
307465    N
307466    Y
307467    Y
307468    Y
307469    Y
307470    Y
307471    Y
307472    Y
307473    Y
307474    Y
307475    N
307476    N
307477    Y
307478    Y
307479    Y
307480    N
307481    Y
307482    Y
307483    Y
307484    N
307485    Y
307486    Y
307487    Y
307488    N
307489    Y
307490    Y
307491    Y
307492    Y
307493    Y
307494    N
307495    N
307496    N
307497    Y
307498    Y
307499    Y
307500    Y
307501    Y
307502    Y
307503    Y
307504    Y
307505    Y
307506    N
307507    Y
307508    Y
307509    Y
307510    N
Name: FLAG_OWN_REALTY, Length: 307511, dtype: object
0         0
1         0
2         0
3         0
4         0
5         0
6         1
7         0
8         0
9         0
10        1
11        0
12        0
13        1
14        0
15        0
16        0
17        1
18        0
19        1
20        0
21        1
22        1
23        0
24        2
25        0
26        0
27        1
28        0
29        0
30        0
31        0
32        0
33        1
34        0
35        0
36        2
37        0
38        0
39        0
40        0
41        0
42        0
43        0
44        0
45        1
46        0
47        0
48        0
49        0
         ..
307461    1
307462    3
307463    0
307464    0
307465    1
307466    0
307467    0
307468    1
307469    0
307470    0
307471    2
307472    1
307473    1
307474    2
307475    1
307476    2
307477    0
307478    0
307479    1
307480    1
307481    0
307482    0
307483    0
307484    0
307485    1
307486    1
307487    0
307488    0
307489    0
307490    0
307491    2
307492    0
307493    0
307494    1
307495    0
307496    0
307497    0
307498    0
307499    0
307500    0
307501    3
307502    1
307503    0
307504    0
307505    0
307506    0
307507    0
307508    0
307509    0
307510    0
Name: CNT_CHILDREN, Length: 307511, dtype: int64
0         202500.000
1         270000.000
2          67500.000
3         135000.000
4         121500.000
5          99000.000
6         171000.000
7         360000.000
8         112500.000
9         135000.000
10        112500.000
11         38419.155
12         67500.000
13        225000.000
14        189000.000
15        157500.000
16        108000.000
17         81000.000
18        112500.000
19         90000.000
20        135000.000
21        202500.000
22        450000.000
23         83250.000
24        135000.000
25         90000.000
26        112500.000
27        112500.000
28        270000.000
29         90000.000
30        292500.000
31        112500.000
32         90000.000
33        360000.000
34        135000.000
35        112500.000
36        198000.000
37        121500.000
38         99000.000
39        180000.000
40        202500.000
41        202500.000
42        135000.000
43        108000.000
44        202500.000
45         90000.000
46        202500.000
47         99000.000
48        130500.000
49        360000.000
             ...
307461    157500.000
307462    135000.000
307463    180000.000
307464     58500.000
307465    180000.000
307466    157500.000
307467    247500.000
307468    135000.000
307469    202500.000
307470     90000.000
307471    112500.000
307472    135000.000
307473     90000.000
307474    135000.000
307475    144000.000
307476    135000.000
307477    360000.000
307478    225000.000
307479    112500.000
307480     81000.000
307481    225000.000
307482    225000.000
307483     99000.000
307484    540000.000
307485    270000.000
307486    292500.000
307487    117000.000
307488    157500.000
307489    225000.000
307490     81000.000
307491     90000.000
307492    585000.000
307493    135000.000
307494    270000.000
307495    180000.000
307496    360000.000
307497    180000.000
307498    198000.000
307499     81000.000
307500    261000.000
307501     81000.000
307502     94500.000
307503    112500.000
307504    153000.000
307505    112500.000
307506    157500.000
307507     72000.000
307508    153000.000
307509    171000.000
307510    157500.000
Name: AMT_INCOME_TOTAL, Length: 307511, dtype: float64
0          406597.5
1         1293502.5
2          135000.0
3          312682.5
4          513000.0
5          490495.5
6         1560726.0
7         1530000.0
8         1019610.0
9          405000.0
10         652500.0
11         148365.0
12          80865.0
13         918468.0
14         773680.5
15         299772.0
16         509602.5
17         270000.0
18         157500.0
19         544491.0
20         427500.0
21        1132573.5
22         497520.0
23         239850.0
24         247500.0
25         225000.0
26         979992.0
27         327024.0
28         790830.0
29         180000.0
30         665892.0
31         512064.0
32         199008.0
33         733315.5
34        1125000.0
35         450000.0
36         641173.5
37         454500.0
38         247275.0
39         540000.0
40        1193580.0
41         604152.0
42         288873.0
43         746280.0
44         661702.5
45         180000.0
46         305221.5
47         260640.0
48        1350000.0
49        1506816.0
            ...
307461     463500.0
307462    1024785.0
307463     247275.0
307464     528633.0
307465     835380.0
307466     599778.0
307467     675000.0
307468     305955.0
307469     703728.0
307470     270000.0
307471     592560.0
307472     808650.0
307473     258709.5
307474     360000.0
307475    1303200.0
307476    1762110.0
307477     796396.5
307478    1125000.0
307479     521280.0
307480    1350000.0
307481     297000.0
307482     500566.5
307483     247275.0
307484     545040.0
307485     180000.0
307486     355536.0
307487    1071909.0
307488     135000.0
307489     521280.0
307490     135000.0
307491    1078200.0
307492    1575000.0
307493     946764.0
307494     479700.0
307495     808650.0
307496     337500.0
307497     270126.0
307498    1312110.0
307499     225000.0
307500    1303812.0
307501     269550.0
307502     225000.0
307503     345510.0
307504     331920.0
307505     225000.0
307506     254700.0
307507     269550.0
307508     677664.0
307509     370107.0
307510     675000.0
Name: AMT_CREDIT, Length: 307511, dtype: float64
0         24700.5
1         35698.5
2          6750.0
3         29686.5
4         21865.5
5         27517.5
6         41301.0
7         42075.0
8         33826.5
9         20250.0
10        21177.0
11        10678.5
12         5881.5
13        28966.5
14        32778.0
15        20160.0
16        26149.5
17        13500.0
18         7875.0
19        17563.5
20        21375.0
21        37561.5
22        32521.5
23        23850.0
24        12703.5
25        11074.5
26        27076.5
27        23827.5
28        57676.5
29         9000.0
30        24592.5
31        25033.5
32        20893.5
33        39069.0
34        32895.0
35        44509.5
36        23157.0
37        15151.5
38        17338.5
39        27000.0
40        35028.0
41        29196.0
42        16258.5
43        42970.5
44        48280.5
45         9000.0
46        17649.0
47        26838.0
48        37255.5
49        49927.5
           ...
307461    16645.5
307462    57222.0
307463    17338.5
307464    27121.5
307465    33259.5
307466    26550.0
307467    33750.0
307468    21888.0
307469    29943.0
307470    10309.5
307471    32274.0
307472    23773.5
307473    20439.0
307474    23004.0
307475    46809.0
307476    48456.0
307477    38443.5
307478    40540.5
307479    31630.5
307480    39474.0
307481    19975.5
307482    34969.5
307483    16479.0
307484    35617.5
307485     9000.0
307486    18283.5
307487    31473.0
307488    13351.5
307489    23089.5
307490     9148.5
307491    31522.5
307492    43443.0
307493    37678.5
307494    46858.5
307495    23773.5
307496    16875.0
307497    12028.5
307498    52168.5
307499    12694.5
307500    35982.0
307501    11871.0
307502    10620.0
307503    17770.5
307504    16096.5
307505    22050.0
307506    27558.0
307507    12001.5
307508    29979.0
307509    20205.0
307510    49117.5
Name: AMT_ANNUITY, Length: 307511, dtype: float64
0          351000.0
1         1129500.0
2          135000.0
3          297000.0
4          513000.0
5          454500.0
6         1395000.0
7         1530000.0
8          913500.0
9          405000.0
10         652500.0
11         135000.0
12          67500.0
13         697500.0
14         679500.0
15         247500.0
16         387000.0
17         270000.0
18         157500.0
19         454500.0
20         427500.0
21         927000.0
22         450000.0
23         225000.0
24         247500.0
25         225000.0
26         702000.0
27         270000.0
28         675000.0
29         180000.0
30         477000.0
31         360000.0
32         180000.0
33         679500.0
34        1125000.0
35         450000.0
36         553500.0
37         454500.0
38         225000.0
39         540000.0
40         855000.0
41         540000.0
42         238500.0
43         675000.0
44         598500.0
45         180000.0
46         252000.0
47         225000.0
48        1350000.0
49        1350000.0
            ...
307461     463500.0
307462     922500.0
307463     225000.0
307464     472500.0
307465     675000.0
307466     477000.0
307467     675000.0
307468     283500.0
307469     607500.0
307470     270000.0
307471     450000.0
307472     675000.0
307473     234000.0
307474     360000.0
307475    1125000.0
307476    1575000.0
307477     643500.0
307478    1125000.0
307479     450000.0
307480    1350000.0
307481     297000.0
307482     472500.0
307483     225000.0
307484     450000.0
307485     180000.0
307486     270000.0
307487     936000.0
307488     135000.0
307489     450000.0
307490     135000.0
307491     900000.0
307492    1575000.0
307493     765000.0
307494     450000.0
307495     675000.0
307496     337500.0
307497     193500.0
307498    1125000.0
307499     225000.0
307500    1138500.0
307501     225000.0
307502     225000.0
307503     247500.0
307504     225000.0
307505     225000.0
307506     225000.0
307507     225000.0
307508     585000.0
307509     319500.0
307510     675000.0
Name: AMT_GOODS_PRICE, Length: 307511, dtype: float64
0           Unaccompanied
1                  Family
2           Unaccompanied
3           Unaccompanied
4           Unaccompanied
5         Spouse, partner
6           Unaccompanied
7           Unaccompanied
8                Children
9           Unaccompanied
10          Unaccompanied
11               Children
12          Unaccompanied
13          Unaccompanied
14          Unaccompanied
15                 Family
16          Unaccompanied
17          Unaccompanied
18                Other_A
19          Unaccompanied
20          Unaccompanied
21          Unaccompanied
22          Unaccompanied
23          Unaccompanied
24          Unaccompanied
25          Unaccompanied
26          Unaccompanied
27                 Family
28          Unaccompanied
29          Unaccompanied
30          Unaccompanied
31                 Family
32          Unaccompanied
33          Unaccompanied
34          Unaccompanied
35          Unaccompanied
36          Unaccompanied
37          Unaccompanied
38          Unaccompanied
39          Unaccompanied
40          Unaccompanied

0              reg oper account
1              reg oper account
2                           NaN
3                           NaN
4                           NaN
5                           NaN
6                           NaN
7                           NaN
8                           NaN
9                           NaN
10                          NaN
11                          NaN
12             reg oper account
13             reg oper account
14             reg oper account
15                          NaN
16                          NaN
17                          NaN
18             reg oper account
19                          NaN
20             reg oper account
21                          NaN
22             reg oper account
23             org spec account
24             reg oper account
25             reg oper account
26                          NaN
27                          NaN
28                          NaN
29             reg oper account
30                          NaN
31                          NaN
32                          NaN
33                          NaN
34             reg oper account
35             reg oper account
36                          NaN
37                          NaN
38                          NaN
39             org spec account
40             org spec account
41                          NaN
42                          NaN
43        reg oper spec account
44                          NaN
45                          NaN
46                          NaN
47                          NaN
48                          NaN
49                          NaN
                  ...
307461         org spec account
307462         org spec account
307463         reg oper account
307464                      NaN
307465         reg oper account
307466         org spec account
307467         org spec account
307468         reg oper account
307469         reg oper account
307470                      NaN
307471                      NaN
307472                      NaN
307473                      NaN
307474         reg oper account
307475                      NaN
307476            not specified
307477                      NaN
307478                      NaN
307479                      NaN
307480                      NaN
307481                      NaN
307482            not specified
307483         reg oper account
307484                      NaN
307485                      NaN
307486                      NaN
307487                      NaN
307488                      NaN
307489         reg oper account
307490                      NaN
307491                      NaN
307492                      NaN
307493                      NaN
307494                      NaN
307495         org spec account
307496                      NaN
307497                      NaN
307498                      NaN
307499                      NaN
307500                      NaN
307501                      NaN
307502                      NaN
307503                      NaN
307504                      NaN
307505         reg oper account
307506         reg oper account
307507         reg oper account
307508         reg oper account
307509                      NaN
307510                      NaN
Name: FONDKAPREMONT_MODE, Length: 307511, dtype: object
0         block of flats
1         block of flats
2                    NaN
3                    NaN
4                    NaN
5                    NaN
6                    NaN
7                    NaN
8                    NaN
9                    NaN
10                   NaN
11                   NaN
12        block of flats
13        block of flats
14        block of flats
15                   NaN
16                   NaN
17                   NaN
18        block of flats
19                   NaN
20        block of flats
21                   NaN
22        block of flats
23        block of flats
24        block of flats
25        block of flats
26        block of flats
27                   NaN
28                   NaN
29        block of flats
30        block of flats
31        block of flats
32        block of flats
33                   NaN
34        block of flats
35        block of flats
36                   NaN
37                   NaN
38        block of flats
39        block of flats
40        block of flats
41                   NaN
42                   NaN
43        block of flats
44                   NaN
45                   NaN
46                   NaN
47                   NaN
48                   NaN
49                   NaN
               ...
307461    block of flats
307462    block of flats
307463    block of flats
307464    block of flats
307465    block of flats
307466    block of flats
307467    block of flats
307468    block of flats
307469    block of flats
307470               NaN
307471               NaN
307472               NaN
307473               NaN
307474    block of flats
307475    block of flats
307476    block of flats
307477    block of flats
307478    block of flats
307479               NaN
307480    block of flats
307481               NaN
307482    block of flats
307483    block of flats
307484               NaN
307485               NaN
307486    block of flats
307487               NaN
307488               NaN
307489    block of flats
307490               NaN
307491               NaN
307492               NaN
307493               NaN
307494               NaN
307495    block of flats
307496               NaN
307497               NaN
307498    block of flats
307499               NaN
307500    block of flats
307501    block of flats
307502               NaN
307503               NaN
307504               NaN
307505    block of flats
307506    block of flats
307507    block of flats
307508    block of flats
307509    block of flats
307510    block of flats
Name: HOUSETYPE_MODE, Length: 307511, dtype: object
0         0.0149
1         0.0714
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12        0.0612
13        0.1417
14        0.3811
15           NaN
16           NaN
17           NaN
18        0.0238
19           NaN
20        0.0530
21           NaN
22        0.0696
23        0.1640
24        0.0967
25        0.0533
26        0.0085
27           NaN
28           NaN
29        0.1227
30        0.0117
31        0.3388
32        0.0684
33           NaN
34        0.0532
35        0.0749
36           NaN
37           NaN
38        0.0786
39        0.0734
40        0.1463
41           NaN
42           NaN
43        0.1903
44           NaN
45           NaN
46           NaN
47           NaN
48           NaN
49           NaN
           ...
307461    0.0766
307462    0.0141
307463    0.3341
307464    0.0068
307465    0.0755
307466    0.0547
307467    0.0576
307468    0.0673
307469    0.0181
307470       NaN
307471       NaN
307472       NaN
307473       NaN
307474    0.0276
307475    0.0557
307476    0.4782
307477    0.0581
307478    0.0284
307479       NaN
307480    0.0026
307481       NaN
307482    0.0272
307483    0.0067
307484       NaN
307485       NaN
307486    0.1976
307487       NaN
307488    0.0407
307489    0.0024
307490       NaN
307491       NaN
307492       NaN
307493       NaN
307494       NaN
307495    0.0700
307496       NaN
307497       NaN
307498    0.1778
307499       NaN
307500    0.0890
307501    0.0149
307502       NaN
307503       NaN
307504       NaN
307505    0.2611
307506    0.2898
307507    0.0214
307508    0.7970
307509    0.0086
307510    0.0718
Name: TOTALAREA_MODE, Length: 307511, dtype: float64
0         Stone, brick
1                Block
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13               Panel
14               Panel
15                 NaN
16                 NaN
17                 NaN
18        Stone, brick
19                 NaN
20        Stone, brick
21                 NaN
22               Panel
23               Mixed
24               Panel
25        Stone, brick
26              Wooden
27                 NaN
28                 NaN
29               Panel
30              Others
31               Block
32               Panel
33                 NaN
34        Stone, brick
35        Stone, brick
36                 NaN
37                 NaN
38        Stone, brick
39        Stone, brick
40        Stone, brick
41                 NaN
42                 NaN
43               Panel
44                 NaN
45                 NaN
46                 NaN
47                 NaN
48                 NaN
49                 NaN
              ...
307461           Panel
307462    Stone, brick
307463           Panel
307464          Wooden
307465           Block
307466    Stone, brick
307467           Panel
307468           Panel
307469    Stone, brick
307470             NaN
307471             NaN
307472             NaN
307473             NaN
307474    Stone, brick
307475           Panel
307476           Panel
307477    Stone, brick
307478           Panel
307479             NaN
307480          Wooden
307481             NaN
307482           Block
307483    Stone, brick
307484             NaN
307485             NaN
307486           Panel
307487             NaN
307488             NaN
307489    Stone, brick
307490             NaN
307491             NaN
307492             NaN
307493             NaN
307494             NaN
307495           Panel
307496             NaN
307497             NaN
307498           Panel
307499             NaN
307500           Panel
307501    Stone, brick
307502             NaN
307503             NaN
307504             NaN
307505           Panel
307506    Stone, brick
307507    Stone, brick
307508           Panel
307509    Stone, brick
307510           Panel
Name: WALLSMATERIAL_MODE, Length: 307511, dtype: object
0          No
1          No
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
11        NaN
12         No
13         No
14         No
15        NaN
16        NaN
17        NaN
18         No
19        NaN
20         No
21        NaN
22         No
23         No
24         No
25         No
26        Yes
27        NaN
28        NaN
29         No
30         No
31         No
32         No
33        NaN
34         No
35         No
36        NaN
37        NaN
38         No
39         No
40         No
41        NaN
42        NaN
43         No
44        NaN
45        NaN
46        NaN
47        NaN
48        NaN
49        NaN
         ...
307461     No
307462     No
307463     No
307464     No
307465     No
307466     No
307467     No
307468     No
307469     No
307470    NaN
307471    NaN
307472    NaN
307473    NaN
307474     No
307475     No
307476     No
307477     No
307478     No
307479    NaN
307480     No
307481    NaN
307482     No
307483     No
307484    NaN
307485    NaN
307486     No
307487    NaN
307488     No
307489    Yes
307490    NaN
307491    NaN
307492    NaN
307493    NaN
307494    NaN
307495     No
307496    NaN
307497    NaN
307498     No
307499    NaN
307500     No
307501     No
307502    NaN
307503    NaN
307504    NaN
307505     No
307506     No
307507     No
307508     No
307509     No
307510     No
Name: EMERGENCYSTATE_MODE, Length: 307511, dtype: object
0          2.0
1          1.0
2          0.0
3          2.0
4          0.0
5          0.0
6          1.0
7          2.0
8          1.0
9          2.0
10         0.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         0.0
17         4.0
18         8.0
19         0.0
20         0.0
21         0.0
22         0.0
23         0.0
24         1.0
25         0.0
26        10.0
27         2.0
28         0.0
29         0.0
30         0.0
31         2.0
32         0.0
33         2.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         1.0
40         0.0
41         4.0
42         1.0
43         0.0
44         1.0
45         1.0
46         0.0
47         4.0
48         0.0
49         1.0
          ...
307461     0.0
307462     0.0
307463     0.0
307464     0.0
307465     4.0
307466     0.0
307467     0.0
307468     2.0
307469    11.0
307470     0.0
307471     0.0
307472     6.0
307473     1.0
307474     0.0
307475     0.0
307476     0.0
307477     0.0
307478     0.0
307479     3.0
307480     1.0
307481     0.0
307482     0.0
307483     1.0
307484     0.0
307485     0.0
307486     0.0
307487     0.0
307488     1.0
307489     1.0
307490     0.0
307491     4.0
307492     0.0
307493     0.0
307494    11.0
307495     0.0
307496     0.0
307497     0.0
307498     0.0
307499     4.0
307500     0.0
307501     2.0
307502     0.0
307503     9.0
307504     0.0
307505     0.0
307506     0.0
307507     0.0
307508     6.0
307509     0.0
307510     0.0
Name: OBS_30_CNT_SOCIAL_CIRCLE, Length: 307511, dtype: float64
0         2.0
1         0.0
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         0.0
10        0.0
11        0.0
12        0.0
13        0.0
14        0.0
15        0.0
16        0.0
17        0.0
18        0.0
19        0.0
20        0.0
21        0.0
22        0.0
23        0.0
24        1.0
25        0.0
26        1.0
27        0.0
28        0.0
29        0.0
30        0.0
31        0.0
32        0.0
33        0.0
34        0.0
35        0.0
36        0.0
37        0.0
38        0.0
39        0.0
40        0.0
41        0.0
42        0.0
43        0.0
44        0.0
45        1.0
46        0.0
47        0.0
48        0.0
49        1.0
         ...
307461    0.0
307462    0.0
307463    0.0
307464    0.0
307465    0.0
307466    0.0
307467    0.0
307468    0.0
307469    2.0
307470    0.0
307471    0.0
307472    0.0
307473    0.0
307474    0.0
307475    0.0
307476    0.0
307477    0.0
307478    0.0
307479    0.0
307480    1.0
307481    0.0
307482    0.0
307483    1.0
307484    0.0
307485    0.0
307486    0.0
307487    0.0
307488    0.0
307489    1.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    0.0
307500    0.0
307501    1.0
307502    0.0
307503    3.0
307504    0.0
307505    0.0
307506    0.0
307507    0.0
307508    0.0
307509    0.0
307510    0.0
Name: DEF_30_CNT_SOCIAL_CIRCLE, Length: 307511, dtype: float64
0          2.0
1          1.0
2          0.0
3          2.0
4          0.0
5          0.0
6          1.0
7          2.0
8          1.0
9          2.0
10         0.0
11         0.0
12         0.0
13         0.0
14         0.0
15         0.0
16         0.0
17         4.0
18         8.0
19         0.0
20         0.0
21         0.0
22         0.0
23         0.0
24         1.0
25         0.0
26        10.0
27         2.0
28         0.0
29         0.0
30         0.0
31         2.0
32         0.0
33         2.0
34         0.0
35         0.0
36         0.0
37         0.0
38         0.0
39         1.0
40         0.0
41         4.0
42         1.0
43         0.0
44         1.0
45         1.0
46         0.0
47         4.0
48         0.0
49         1.0
          ...
307461     0.0
307462     0.0
307463     0.0
307464     0.0
307465     4.0
307466     0.0
307467     0.0
307468     2.0
307469    11.0
307470     0.0
307471     0.0
307472     6.0
307473     1.0
307474     0.0
307475     0.0
307476     0.0
307477     0.0
307478     0.0
307479     3.0
307480     1.0
307481     0.0
307482     0.0
307483     1.0
307484     0.0
307485     0.0
307486     0.0
307487     0.0
307488     1.0
307489     1.0
307490     0.0
307491     4.0
307492     0.0
307493     0.0
307494    11.0
307495     0.0
307496     0.0
307497     0.0
307498     0.0
307499     4.0
307500     0.0
307501     2.0
307502     0.0
307503     9.0
307504     0.0
307505     0.0
307506     0.0
307507     0.0
307508     6.0
307509     0.0
307510     0.0
Name: OBS_60_CNT_SOCIAL_CIRCLE, Length: 307511, dtype: float64
0         2.0
1         0.0
2         0.0
3         0.0
4         0.0
5         0.0
6         0.0
7         0.0
8         0.0
9         0.0
10        0.0
11        0.0
12        0.0
13        0.0
14        0.0
15        0.0
16        0.0
17        0.0
18        0.0
19        0.0
20        0.0
21        0.0
22        0.0
23        0.0
24        0.0
25        0.0
26        0.0
27        0.0
28        0.0
29        0.0
30        0.0
31        0.0
32        0.0
33        0.0
34        0.0
35        0.0
36        0.0
37        0.0
38        0.0
39        0.0
40        0.0
41        0.0
42        0.0
43        0.0
44        0.0
45        1.0
46        0.0
47        0.0
48        0.0
49        1.0
         ...
307461    0.0
307462    0.0
307463    0.0
307464    0.0
307465    0.0
307466    0.0
307467    0.0
307468    0.0
307469    0.0
307470    0.0
307471    0.0
307472    0.0
307473    0.0
307474    0.0
307475    0.0
307476    0.0
307477    0.0
307478    0.0
307479    0.0
307480    0.0
307481    0.0
307482    0.0
307483    1.0
307484    0.0
307485    0.0
307486    0.0
307487    0.0
307488    0.0
307489    0.0
307490    0.0
307491    0.0
307492    0.0
307493    0.0
307494    0.0
307495    0.0
307496    0.0
307497    0.0
307498    0.0
307499    0.0
307500    0.0
307501    1.0
307502    0.0
307503    2.0
307504    0.0
307505    0.0
307506    0.0
307507    0.0
307508    0.0
307509    0.0
307510    0.0
Name: DEF_60_CNT_SOCIAL_CIRCLE, Length: 307511, dtype: float64
0        -1134.0
1         -828.0
2         -815.0
3         -617.0
4        -1106.0
5        -2536.0
6        -1562.0
7        -1070.0
8            0.0
9        -1673.0
10        -844.0
11       -2396.0
12       -2370.0
13          -4.0
14        -188.0
15        -925.0
16          -3.0
17       -2811.0
18        -239.0
19       -1850.0
20        -296.0
21           0.0
22        -468.0
23        -795.0
24          -4.0
25           0.0
26        -161.0
27          -2.0
28        -849.0
29        -599.0
30       -1634.0
31        -397.0
32       -2766.0
33        -697.0
34       -3019.0
35       -1285.0
36       -2411.0
37       -1541.0
38           0.0
39        -540.0
40       -1075.0
41        -458.0
42       -1480.0
43        -491.0
44        -556.0
45        -462.0
46        -649.0
47       -1247.0
48        -784.0
49       -1498.0
           ...
307461   -1669.0
307462    -656.0
307463   -1573.0
307464   -1457.0
307465   -1135.0
307466   -2492.0
307467    -148.0
307468    -499.0
307469   -1667.0
307470   -2190.0
307471    -385.0
307472   -1831.0
307473    -637.0
307474   -2159.0
307475   -1492.0
307476   -2538.0
307477   -1353.0
307478    -549.0
307479    -396.0
307480   -1594.0
307481   -2941.0
307482    -611.0
307483   -1775.0
307484   -1578.0
307485    -336.0
307486       0.0
307487    -846.0
307488    -610.0
307489    -307.0
307490    -439.0
307491   -1357.0
307492       0.0
307493    -249.0
307494    -367.0
307495   -2919.0
307496    -826.0
307497   -1344.0
307498    -734.0
307499   -1511.0
307500   -1459.0
307501    -448.0
307502   -1516.0
307503   -2315.0
307504       0.0
307505       0.0
307506    -273.0
307507       0.0
307508   -1909.0
307509    -322.0
307510    -787.0
Name: DAYS_LAST_PHONE_CHANGE, Length: 307511, dtype: float64
0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
30        0
31        0
32        0
33        0
34        0
35        0
36        0
37        0
38        0
39        0
40        0
41        0
42        0
43        0
44        0
45        0
46        0
47        0
48        0
49        0
         ..
307461    0
307462    0
307463    0

In [30]:
for col in app_train.columns:
    print(col)

SK_ID_CURR
TARGET
NAME_CONTRACT_TYPE
CODE_GENDER
FLAG_OWN_CAR
FLAG_OWN_REALTY
CNT_CHILDREN
AMT_INCOME_TOTAL
AMT_CREDIT
AMT_ANNUITY
AMT_GOODS_PRICE
NAME_TYPE_SUITE
NAME_INCOME_TYPE
NAME_EDUCATION_TYPE
NAME_FAMILY_STATUS
NAME_HOUSING_TYPE
REGION_POPULATION_RELATIVE
DAYS_BIRTH
DAYS_EMPLOYED
DAYS_REGISTRATION
DAYS_ID_PUBLISH
OWN_CAR_AGE
FLAG_MOBIL
FLAG_EMP_PHONE
FLAG_WORK_PHONE
FLAG_CONT_MOBILE
FLAG_PHONE
FLAG_EMAIL
OCCUPATION_TYPE
CNT_FAM_MEMBERS
REGION_RATING_CLIENT
REGION_RATING_CLIENT_W_CITY
WEEKDAY_APPR_PROCESS_START
HOUR_APPR_PROCESS_START
REG_REGION_NOT_LIVE_REGION
REG_REGION_NOT_WORK_REGION
LIVE_REGION_NOT_WORK_REGION
REG_CITY_NOT_LIVE_CITY
REG_CITY_NOT_WORK_CITY
LIVE_CITY_NOT_WORK_CITY
ORGANIZATION_TYPE
EXT_SOURCE_1
EXT_SOURCE_2
EXT_SOURCE_3
APARTMENTS_AVG
BASEMENTAREA_AVG
YEARS_BEGINEXPLUATATION_AVG
YEARS_BUILD_AVG
COMMONAREA_AVG
ELEVATORS_AVG
ENTRANCES_AVG
FLOORSMAX_AVG
FLOORSMIN_AVG
LANDAREA_AVG
LIVINGAPARTMENTS_AVG
LIVINGAREA_AVG
NONLIVINGAPARTMENTS_AVG
NONLIVINGAREA_AVG
APARTMENTS_MODE
BASEMENTAREA_MODE
YEARS_BEGINEXPLUATATION_MODE
YEARS_BUILD_MODE
COMMONAREA_MODE
ELEVATORS_MODE
ENTRANCES_MODE
FLOORSMAX_MODE
FLOORSMIN_MODE
LANDAREA_MODE
LIVINGAPARTMENTS_MODE
LIVINGAREA_MODE
NONLIVINGAPARTMENTS_MODE
NONLIVINGAREA_MODE
APARTMENTS_MEDI
BASEMENTAREA_MEDI
YEARS_BEGINEXPLUATATION_MEDI
YEARS_BUILD_MEDI
COMMONAREA_MEDI
ELEVATORS_MEDI
ENTRANCES_MEDI
FLOORSMAX_MEDI
FLOORSMIN_MEDI
LANDAREA_MEDI
LIVINGAPARTMENTS_MEDI
LIVINGAREA_MEDI
NONLIVINGAPARTMENTS_MEDI
NONLIVINGAREA_MEDI
FONDKAPREMONT_MODE
HOUSETYPE_MODE
TOTALAREA_MODE
WALLSMATERIAL_MODE
EMERGENCYSTATE_MODE
OBS_30_CNT_SOCIAL_CIRCLE
DEF_30_CNT_SOCIAL_CIRCLE
OBS_60_CNT_SOCIAL_CIRCLE
DEF_60_CNT_SOCIAL_CIRCLE
DAYS_LAST_PHONE_CHANGE
FLAG_DOCUMENT_2
FLAG_DOCUMENT_3
FLAG_DOCUMENT_4
FLAG_DOCUMENT_5
FLAG_DOCUMENT_6
FLAG_DOCUMENT_7
FLAG_DOCUMENT_8
FLAG_DOCUMENT_9
FLAG_DOCUMENT_10
FLAG_DOCUMENT_11
FLAG_DOCUMENT_12
FLAG_DOCUMENT_13
FLAG_DOCUMENT_14
FLAG_DOCUMENT_15
FLAG_DOCUMENT_16
FLAG_DOCUMENT_17
FLAG_DOCUMENT_18
FLAG_DOCUMENT_19
FLAG_DOCUMENT_20
FLAG_DOCUMENT_21
AMT_REQ_CREDIT_BUREAU_HOUR
AMT_REQ_CREDIT_BUREAU_DAY
AMT_REQ_CREDIT_BUREAU_WEEK
AMT_REQ_CREDIT_BUREAU_MON
AMT_REQ_CREDIT_BUREAU_QRT
AMT_REQ_CREDIT_BUREAU_YEAR

#### 截取部分資料

In [31]:
fliter = (app_train["NAME_CONTRACT_TYPE"] == "Cash loans")
app_train[fliter]

        SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  NAME_TYPE_SUITE      NAME_INCOME_TYPE            NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS    NAME_HOUSING_TYPE  REGION_POPULATION_RELATIVE  DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  DAYS_ID_PUBLISH  OWN_CAR_AGE  FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  FLAG_CONT_MOBILE  FLAG_PHONE  FLAG_EMAIL        OCCUPATION_TYPE  CNT_FAM_MEMBERS  REGION_RATING_CLIENT  REGION_RATING_CLIENT_W_CITY WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START  REG_REGION_NOT_LIVE_REGION  REG_REGION_NOT_WORK_REGION  LIVE_REGION_NOT_WORK_REGION  REG_CITY_NOT_LIVE_CITY  REG_CITY_NOT_WORK_CITY  LIVE_CITY_NOT_WORK_CITY       ORGANIZATION_TYPE  EXT_SOURCE_1  EXT_SOURCE_2  EXT_SOURCE_3  APARTMENTS_AVG  BASEMENTAREA_AVG  YEARS_BEGINEXPLUATATION_AVG  YEARS_BUILD_AVG  COMMONAREA_AVG  ELEVATORS_AVG  ENTRANCES_AVG  FLOORSMAX_AVG  FLOORSMIN_AVG  LANDAREA_AVG  LIVINGAPARTMENTS_AVG  LIVINGAREA_AVG  NONLIVINGAPARTMENTS_AVG  NONLIVINGAREA_AVG  APARTMENTS_MODE  BASEMENTAREA_MODE  YEARS_BEGINEXPLUATATION_MODE  YEARS_BUILD_MODE  COMMONAREA_MODE  ELEVATORS_MODE  ENTRANCES_MODE  FLOORSMAX_MODE  FLOORSMIN_MODE  LANDAREA_MODE  LIVINGAPARTMENTS_MODE  LIVINGAREA_MODE  NONLIVINGAPARTMENTS_MODE  NONLIVINGAREA_MODE  APARTMENTS_MEDI  BASEMENTAREA_MEDI  YEARS_BEGINEXPLUATATION_MEDI  YEARS_BUILD_MEDI  COMMONAREA_MEDI  ELEVATORS_MEDI  ENTRANCES_MEDI  FLOORSMAX_MEDI  FLOORSMIN_MEDI  LANDAREA_MEDI  LIVINGAPARTMENTS_MEDI  LIVINGAREA_MEDI  NONLIVINGAPARTMENTS_MEDI  NONLIVINGAREA_MEDI     FONDKAPREMONT_MODE  HOUSETYPE_MODE  TOTALAREA_MODE WALLSMATERIAL_MODE EMERGENCYSTATE_MODE  OBS_30_CNT_SOCIAL_CIRCLE  DEF_30_CNT_SOCIAL_CIRCLE  OBS_60_CNT_SOCIAL_CIRCLE  DEF_60_CNT_SOCIAL_CIRCLE  DAYS_LAST_PHONE_CHANGE  FLAG_DOCUMENT_2  FLAG_DOCUMENT_3  FLAG_DOCUMENT_4  FLAG_DOCUMENT_5  FLAG_DOCUMENT_6  FLAG_DOCUMENT_7  FLAG_DOCUMENT_8  FLAG_DOCUMENT_9  FLAG_DOCUMENT_10  FLAG_DOCUMENT_11  FLAG_DOCUMENT_12  FLAG_DOCUMENT_13  FLAG_DOCUMENT_14  FLAG_DOCUMENT_15  FLAG_DOCUMENT_16  FLAG_DOCUMENT_17  FLAG_DOCUMENT_18  FLAG_DOCUMENT_19  FLAG_DOCUMENT_20  FLAG_DOCUMENT_21  AMT_REQ_CREDIT_BUREAU_HOUR  AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  AMT_REQ_CREDIT_BUREAU_MON  AMT_REQ_CREDIT_BUREAU_QRT  AMT_REQ_CREDIT_BUREAU_YEAR
0           100002       1         Cash loans           M            N               Y             0        202500.000    406597.5      24700.5         351000.0    Unaccompanied               Working  Secondary / secondary special  Single / not married    House / apartment                    0.018801       -9461           -637            -3648.0            -2120          NaN           1               1                0                 1           1           0               Laborers              1.0                     2                            2                  WEDNESDAY                       10                           0                           0                            0                       0                       0                        0  Business Entity Type 3      0.083037      0.262949      0.139376          0.0247            0.0369                       0.9722           0.6192          0.0143           0.00         0.0690         0.0833         0.1250        0.0369                0.0202          0.0190                   0.0000             0.0000           0.0252             0.0383                        0.9722            0.6341           0.0144          0.0000          0.0690          0.0833          0.1250         0.0377                 0.0220           0.0198                    0.0000              0.0000           0.0250             0.0369                        0.9722            0.6243           0.0144            0.00          0.0690          0.0833          0.1250         0.0375                 0.0205           0.0193                    0.0000              0.0000       reg oper account  block of flats          0.0149       Stone, brick                  No                       2.0                       2.0                       2.0                       2.0                 -1134.0                0                1                0                0                0                0                0                0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                         0.0                        0.0                         0.0                        0.0                        0.0                         1.0
1           100003       0         Cash loans           F            N               N             0        270000.000   1293502.5      35698.5        1129500.0           Family         State servant               Higher education               Married    House / apartment                    0.003541      -16765          -1188            -1186.0             -291          NaN           1               1                0                 1           1           0             Core staff              2.0                     1                            1                     MONDAY                       11                           0                           0                            0                       0                       0                        0                  School      0.311267      0.622246           NaN          0.0959            0.0529                       0.9851           0.7960          0.0605           0.08         0.0345         0.2917         0.3333        0.0130                0.0773          0.0549                   0.0039             0.0098           0.0924             0.0538                        0.9851            0.8040           0.0497          0.0806          0.0345          0.2917          0.3333         0.0128                 0.0790           0.0554                    0.0000              0.0000           0.0968             0.0529                        0.9851            0.7987           0.0608            0.08          0.0345          0.2917          0.3333         0.0132                 0.0787           0.0558                    0.0039              0.0100       reg oper account  block of flats          0.0714              Block                  No                       1.0                       0.0                       1.0                       0.0                  -828.0                0                1                0                0                0                0                0                0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                         0.0                        0.0                         0.0                        0.0                        0.0                         0.0
3           100006       0         Cash loans           F            N               Y             0        135000.000    312682.5      29686.5         297000.0    Unaccompanied               Working  Secondary / secondary special        Civil marriage    House / apartment                    0.008019      -19005          -3039            -9833.0            -2437          NaN           1               1                0                 1           0           0               Laborers              2.0                     2                            2                  WEDNESDAY                       17                           0                           0                            0                       0                       0                        0  Business Entity Type 3           NaN      0.650442           NaN             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN                   NaN             NaN                      NaN                NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN                    NaN             NaN             NaN                NaN                 NaN                       2.0                       0.0                       2.0                       0.0                  -617.0                0                1                0                0                0                0                0                0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                         NaN                        NaN                         NaN                        NaN                        NaN                         NaN
4           100007       0         Cash loans           M            N               Y             0        121500.000    513000.0      21865.5         513000.0    Unaccompanied               Working  Secondary / secondary special  Single / not married    House / apartment                    0.028663      -19932          -3038            -4311.0            -3458          NaN           1               1                0                 1           0           0             Core staff              1.0                     2                            2                   THURSDAY                       11                           0                           0                            0                       0                       1                        1                Religion           NaN      0.322738           NaN             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN                   NaN             NaN                      NaN                NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN                    NaN             NaN             NaN                NaN                 NaN                       0.0                       0.0                       0.0                       0.0                 -1106.0                0                0                0                0                0                0                1                0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                         0.0                        0.0                         0.0                        0.0                        0.0                         0.0
5           100008       0         Cash loans           M            N               Y             0         99000.000    490495.5      27517.5         454500.0  Spouse, partner         State servant  Secondary / secondary special               Married    House / apartment                    0.035792      -16941          -1588            -4970.0             -477          NaN           1               1                1                 1           1           0               Laborers              2.0                     2                            2                  WEDNESDAY                       16                           0                           0                            0                       0                       0                        0                   Other           NaN      0.354225      0.621226             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN                   NaN             NaN                      NaN                NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN                    NaN             NaN             NaN                NaN                 NaN                       0.0                       0.0                       0.0                       0.0                 -2536.0                0                1                0                0                0                0                0                0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                         0.0                        0.0                         0.0                        0.0                        1.0                         1.0
6           100009       0         Cash loans           F            Y               Y             1        171000.000   1560726.0      41301.0        1395000.0    Unaccompanied  Commercial associate               Higher education               Married    House / apartment                    0.035792      -13778          -3130            -1213.0             -619         17.0           1               1                0                 1           1           0            Accountants              3.0                     2                            2                     SUNDAY                       16                           0                           0                            0                       0                       0                        0  Business Entity Type 3      0.774761      0.724000      0.492060             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN                   NaN             NaN                      NaN                NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN                    NaN             NaN             NaN                NaN                 NaN                       1.0                       0.0                       1.0                       0.0                 -1562.0                0                0                0                0                0                0                1                0                 0                 0                 0                 0                 1                 0                 0                 0                 0                 0                 0                 0                         0.0                        0.0                         0.0                        1.0                        1.0                         2.0
7           100010       0         Cash loans           M            Y               Y             0        360000.000   1530000.0      42075.0        1530000.0    Unaccompanied         State servant               Higher education               Married    House / apartment                    0.003122      -18850           -449            -4597.0            -2379          8.0           1               1                1                 1           0           0               Managers              2.0                     3                            3                     MONDAY                       16                           0                           0                            0                       0                       1                        1                   Other           NaN      0.714279      0.540654             NaN               NaN                          NaN              NaN             NaN            NaN            NaN            NaN            NaN           NaN                   NaN             NaN                      NaN                NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN              NaN                NaN                           NaN               NaN              NaN             NaN             NaN             NaN             NaN            NaN                    NaN              NaN                       NaN                 NaN                    NaN             NaN             NaN                NaN                 NaN                       2.0                       0.0                       2.0                       0.0                 -1070.0                0                1                0                0                0                0                0                0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                 0                         0.0                        0.0                         0.0                        0.0                        0.0                         0.0

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子